server:
  port: 8080

spring:
  application:
    name: tbank-api

selenium:
  driver:
    implicit-wait: 10
    page-load-timeout: 30
    script-timeout: 30
    headless: true
  
tbank:
  base-url: "https://www.tbank.ru"
  login-url: "https://www.tbank.ru/login"

logging:
  level:
    ru.holeyko.tbankapi: DEBUG
    org.selenium: WARN
